application: proyeccion-colombia1
version: 2
runtime: python27
api_version: 1

threadsafe: false

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- node_modules/.*$

handlers:
- url: /favicon.ico
  static_files: assets/img/favicon.ico
  upload: assets/img/favicon.ico
  
- url: /assets
  static_dir: assets
  
- url: /images
  static_dir: images

- url: .*
  script: main.py

libraries:
- name: django
  version: "1.3"
  
env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
